### ISSUE TITLE
单独升级hessian到3.3.8报错

### ISSUE THREAD

**Issue by Misakami** [sofastack/sofa-hessian#82]
环境 
jdk 8
sofa-rpc-all 5.5.0 
sofa-hessian 3.3.8

错误提示：
![image](https://user-images.githubusercontent.com/22981008/228104477-f09f6911-a25b-4749-8068-f4675d5a91d8.png)
这段代码报错
![cd6eda60-cd08-11ed-93b2-973457102b58](https://user-images.githubusercontent.com/22981008/228104600-b588e8a6-53ad-4cf9-9c30-262aca1a1758.png)
为3.3.8新加的NameBlackListFilter内LoggerSpaceManager.getLoggerBySpace("HessianSerializeLog", "com.alipay.sofa.middleware.config")。该怎么解决

**Comment by OrezzerO** [comment]
see #78
